### ISSUE TITLE
how to write a pid component

### ISSUE THREAD

**Issue by hzgzh** [zekeriyasari/Jusdl.jl#21]
don't know how to represent the differential part of pid algorithm,how to differential the input, can the author give some example

**Comment by zekeriyasari** [comment]
Thank you for filing this issue @hzgzh 

I included `Differentiator` and `Integrator` components to the `Jusdl`.  Here are the examples.

* Differentiation 
```julia 
using Jusdl 
using Plots 

model = Model(clock=Clock(0, 0.01, 4π)) 
addnode!(model, FunctionGenerator(t -> sin(t)), label=:gen)
addnode!(model, Differentiator(), label=:dif)
addnode!(model, Writer(Inport(2)), label=:writer)
addbranch!(model, :gen => :dif, 1 => 1)
addbranch!(model, :gen => :writer, 1 => 1)
addbranch!(model, :dif => :writer, 1 => 2)
simulate!(model)

t, x = read(getnode(model, :writer).component)
scatter(t, x[:, 1], markersize=2, label=:gen)
scatter!(t, x[:, 2], markersize=2, label=:dif)
```

![diff](https://user-images.githubusercontent.com/24751240/81756983-0239cf80-94c6-11ea-80a6-e3c7a5869386.png)

* Integration
```julia 
using Jusdl 
using Plots 

model = Model(clock=Clock(0, 0.001, 4)) 
addnode!(model, FunctionGenerator(t -> 2 * t), label=:gen)
addnode!(model, Integrator(), label=:integ)
addnode!(model, Writer(Inport(2)), label=:writer)
addbranch!(model, :gen => :integ, 1 => 1)
addbranch!(model, :gen => :writer, 1 => 1)
addbranch!(model, :integ => :writer, 1 => 2)
simulate!(model)

t, x = read(getnode(model, :writer).component)
scatter(t, x[:, 1], markersize=2, label=:gen)
scatter!(t, x[:, 2], markersize=2, label=:integ)
```
![integ](https://user-images.githubusercontent.com/24751240/81757074-45943e00-94c6-11ea-981a-1a68ea158b34.png)

**Remainder** : Do not forget to check out the master branch for the updates! 
```julia 
] add Jusdl#master
```

I will also include a complete PID controller example to the docs. So, thank you for your contribution by opening this issue.

**Comment by hzgzh** [comment]
It's work.thank very much,wish this software can instead simulink.
