### ISSUE TITLE
add Delay component？

### ISSUE THREAD

**Issue by hzgzh** [zekeriyasari/Jusdl.jl#24]
```
struct Delay{OF, IB, OB, TR, HS, CB, DL,IP} <: AbstractStaticSystem
    @generic_static_system_fields
    τ::KD
    interp::IP
    intial_value:IV
    function Delay(τ=1,intial_value=0; callbacks=nothing, name=Symbol())
                
        input = Inport() 
        output = Outport()
        trigger = Inpin() 
        handshake = Outpin{Bool}()
        function outputfunc(uu, tt)
            update_interpolator(interp,uu,tt)
            if tt<τ
                return intial_value
            end
            return interpolate(interp,tt-τ)
        end
        new{typeof(outputfunc), typeof(input), typeof(output), typeof(trigger), typeof(handshake), typeof(callbacks), typeof(kd), typeof(t), typeof(u)}(outputfunc, input, output, trigger, handshake, callbacks, name, uuid4(), kd, t, u)
    end
end
```
I think the Delay component like this,but don't know how to make it work

**Comment by zekeriyasari** [comment]
To delay a delay, you can use [`Memory`](https://github.com/zekeriyasari/Jusdl.jl/blob/76fe9468a75a3fc5c6640554e3d32ab87de897ba/src/components/systems/staticsystems/staticsystems.jl#L162-L181) component. See an [example](https://github.com/zekeriyasari/Jusdl.jl/blob/master/example/memory_operation.jl) from the example directory. If you run the script, you get the following plots. 

![memory](https://user-images.githubusercontent.com/24751240/82051322-53161780-96c2-11ea-8444-d3dc311891d6.png)

In the plots, just the first 5 samples are plotted. Note that the output of `:gen` is delayed for one step size (1 second). You can give get any amount of delay by using the `Memory` block properly.

**Comment by hzgzh** [comment]
Thank very much,another question is if I want do some model parameter estimate using Optim.jl,because in staticsytem.jl the type like "Gain","Memory"," Differentiator" is immutable, so the component parameter can't change,can the type change to mutable

**Comment by zekeriyasari** [comment]
In the context of `Jusdl`,  `StaticSystems` like those need not be mutable. But, I will consider making them mutable after carrying out some benchmarks.
