### ISSUE TITLE
Wrong doc

### ISSUE THREAD

**Issue by ohmsweetohm1** [zekeriyasari/Jusdl.jl#33]
https://github.com/zekeriyasari/Jusdl.jl/blob/4639d89d82d96b896e19121a63e10bc7472da760/src/components/systems/dynamicalsystems/odesystems.jl#L47

Should be `def_ode_system` I think. Also `state` seems to be missing.

**Comment by zekeriyasari** [comment]
It should definitely be `@def_ode_system`. And, again yes, `state` is missing. Will correct the docs. Thank you.
